// <auto-generated />
using GerenciamentoDeFuncionarios.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GerenciamentoDeFuncionarios.Migrations
{
    [DbContext(typeof(FuncionariosContext))]
    [Migration("20191023235129_LotacaoID2")]
    partial class LotacaoID2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("ResponsavelId");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LotacaoId");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("LotacaoId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AreaId");

                    b.Property<string>("Descricao");

                    b.Property<int?>("ExecutorId");

                    b.Property<DateTime?>("Fim");

                    b.Property<DateTime>("Inicio");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ExecutorId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Departamento", b =>
                {
                    b.HasOne("GerenciamentoDeFuncionarios.Models.Funcionario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Funcionario", b =>
                {
                    b.HasOne("GerenciamentoDeFuncionarios.Models.Departamento", "Lotacao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("LotacaoId");
                });

            modelBuilder.Entity("GerenciamentoDeFuncionarios.Models.Tarefa", b =>
                {
                    b.HasOne("GerenciamentoDeFuncionarios.Models.Departamento", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("GerenciamentoDeFuncionarios.Models.Funcionario", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");
                });
#pragma warning restore 612, 618
        }
    }
}
