// <auto-generated />
namespace ORMEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Casas201908192143 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Casas201908192143));
        
        string IMigrationMetadata.Id
        {
            get { return "201908200043575_Casas201908192143"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
