// <auto-generated />
namespace CadastroFuncionarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedCorrigidaAgoraVai201909112026 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedCorrigidaAgoraVai201909112026));
        
        string IMigrationMetadata.Id
        {
            get { return "201909112326594_SeedCorrigidaAgoraVai201909112026"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
