// <auto-generated />
namespace Calcados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddClasseItem201909302057 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClasseItem201909302057));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302357366_AddClasseItem201909302057"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
